---
title: "BCO6672 - Lab 3"
author: "MariaProkofieva"
date: "25/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tutorial 3

```
Learning objectives

1. To familiarise yourself with Tableau. 

2. To learn basic concepts elements in Tableau

3. To be able to prep data in Tableau.
```

#### Datasets

Please see VU Collaborate for datasets that are used in this tutorial

####  Resources

We will be using [this ethepad](https://video.etherpad.com/p/bco6007) to document the progress


### Starting with Tableau - interface  (10 minutes)

Start `Tableau` and familiarise yourself with the interface. `Tableau` has intuitive interface, so lots of elements are vary familiar there.

Watch [this tutorial](https://help.tableau.com/current/pro/desktop/en-us/environment_workspace.htm) 


**Questions**:

### Basic elements and simple data management in `Tableau` (10 minutes + 15 minutes)

Learn about the basic workflow in Tableau and complete the tutorial [here](https://help.tableau.com/current/guides/get-started-tutorial/en-us/get-started-tutorial-home.htm) 


**Key take-aways**:

- It’s pretty much all drag and drop!

- You import data in the `Data Source` tab.

- Your work is in worksheets. Each worksheet is in a tab at the bottom of the window (Excel style).

- Tableau splits your data columns into dimensions and measures. It infers the type of data based on a column’s contents. It shows little symbols next to each variable name to represent numeric, string, geo, boolean, and date data types. 

- `Dimensions` are **qualitative (categorical)** variables, including strings and dates. They are discrete, by default, colored blue.

- `Measures` are **quantitative (numeric)** variables that you can sum and average. They are continuous, by default, colored green.

- Tableau assumes you want to sum measures any time you use them, by default. You can change the aggregation function with a right click on that variable.

- The `Marks` card controls many visualization aspects. Drag variables from the left side bar to the Marks card to control color, text, tooltips, and more. Use it after your rows and columns are set.

- There are many chart options - `Tableau` makes suggestions in the expandable `Show Me` menu to the right. Suggestions are based on the current variables used in the worksheet.

- The formatting can be changed. Right click on whatever you want to change and you’ll see options.

- To filtering data you  drag a variable to the `filter` area. Right click on the pill and choose `Show Filter` to create an interactive filter.

- You can create a `group`, `set`, or `calculated field` by right clicking on a variable. These options allow you to group data and find more insights.

- You can make dashboards by dragging and dropping finished worksheets onto a new dashboard. Then viewers can sort and filter your charts, but they can’t break your dashboards.

**Questions**:

- What are dimensions?

- What are measures?

- Can the same variable be a dimension in one case and a measure in another? Give examples


### Working with messy data in `Tableau` (10 minutes)

Complete the tutorial here


**Questions**:

### Tasks:

1. Upload the file `avocado.csv` located in the tutorial folder and examine it. How can the data quality there can be improved. 

Clean the data and 

2. What variables can you use for dimensions and measures? 

3. Develop three visualisations with different set of dimensions and measures?
Select one visualisation and discuss it your working group. 

Ask your peers to identify 3 positives and 3 negatives about your chosen visualisation.

Improve your visualization based on the feedback received and publish it.


### Resources: 




